import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: {
          app: 'rgb(var(--color-bg-app) / <alpha-value>)',
          subtle: 'rgb(var(--color-bg-subtle) / <alpha-value>)',
          elevated: 'rgb(var(--color-bg-elevated) / <alpha-value>)',
          inverse: 'rgb(var(--color-bg-inverse) / <alpha-value>)',
          secondary: 'rgb(var(--color-bg-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--color-bg-tertiary) / <alpha-value>)',
        },
        surface: {
          DEFAULT: 'rgb(var(--color-surface) / <alpha-value>)',
          raised: 'rgb(var(--color-surface-raised) / <alpha-value>)',
          sunken: 'rgb(var(--color-surface-sunken) / <alpha-value>)',
          glass: 'rgb(var(--color-surface-glass) / <alpha-value>)',
          selected: 'rgb(var(--color-surface-selected) / <alpha-value>)',
        },
        border: {
          DEFAULT: 'rgb(var(--color-border) / <alpha-value>)',
          strong: 'rgb(var(--color-border-strong) / <alpha-value>)',
          subtle: 'rgb(var(--color-border-subtle) / <alpha-value>)',
          focus: 'rgb(var(--color-border-focus) / <alpha-value>)',
        },
        content: {
          primary: 'rgb(var(--color-content-primary) / <alpha-value>)',
          secondary: 'rgb(var(--color-content-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--color-content-tertiary) / <alpha-value>)',
          inverse: 'rgb(var(--color-content-inverse) / <alpha-value>)',
          muted: 'rgb(var(--color-content-muted) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--color-accent) / <alpha-value>)',
          hover: 'rgb(var(--color-accent-hover) / <alpha-value>)',
          active: 'rgb(var(--color-accent-active) / <alpha-value>)',
          secondary: 'rgb(var(--color-accent-secondary) / <alpha-value>)',
          glow: 'rgb(var(--color-accent-glow) / <alpha-value>)',
          light: 'rgb(var(--color-accent-light) / <alpha-value>)',
          soft: 'rgb(var(--color-accent-soft) / <alpha-value>)',
          text: 'rgb(var(--color-accent-text) / <alpha-value>)',
        },
        danger: {
          DEFAULT: 'rgb(var(--color-danger) / <alpha-value>)',
          light: 'rgb(var(--color-danger-light) / <alpha-value>)',
          text: 'rgb(var(--color-danger-text) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'rgb(var(--color-warning) / <alpha-value>)',
          light: 'rgb(var(--color-warning-light) / <alpha-value>)',
          text: 'rgb(var(--color-warning-text) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--color-success) / <alpha-value>)',
          light: 'rgb(var(--color-success-light) / <alpha-value>)',
          text: 'rgb(var(--color-success-text) / <alpha-value>)',
        },
        info: {
          DEFAULT: 'rgb(var(--color-info) / <alpha-value>)',
          light: 'rgb(var(--color-info-light) / <alpha-value>)',
          text: 'rgb(var(--color-info-text) / <alpha-value>)',
        },
        film: {
          DEFAULT: 'rgb(var(--color-film) / <alpha-value>)',
          light: 'rgb(var(--color-film-light) / <alpha-value>)',
          text: 'rgb(var(--color-film-text) / <alpha-value>)',
        },
        series: {
          DEFAULT: 'rgb(var(--color-series) / <alpha-value>)',
          light: 'rgb(var(--color-series-light) / <alpha-value>)',
          text: 'rgb(var(--color-series-text) / <alpha-value>)',
        },
        game: {
          DEFAULT: 'rgb(var(--color-game) / <alpha-value>)',
          light: 'rgb(var(--color-game-light) / <alpha-value>)',
          text: 'rgb(var(--color-game-text) / <alpha-value>)',
        },
        book: {
          DEFAULT: 'rgb(var(--color-book) / <alpha-value>)',
          light: 'rgb(var(--color-book-light) / <alpha-value>)',
          text: 'rgb(var(--color-book-text) / <alpha-value>)',
        },
        status: {
          want: 'rgb(var(--color-status-want) / <alpha-value>)',
          progress: 'rgb(var(--color-status-progress) / <alpha-value>)',
          done: 'rgb(var(--color-status-done) / <alpha-value>)',
        },
        app: {
          bg: 'rgb(var(--color-bg-app) / <alpha-value>)',
          text: 'rgb(var(--color-content-primary) / <alpha-value>)',
          accent: 'rgb(var(--color-accent) / <alpha-value>)',
          border: 'rgb(var(--color-border) / <alpha-value>)',
          surface: 'rgb(var(--color-surface) / <alpha-value>)',
          muted: 'rgb(var(--color-content-secondary) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Instrument Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        xs: '0 1px 2px rgba(16, 24, 40, 0.04)',
        sm: '0 4px 12px rgba(16, 24, 40, 0.06)',
        soft: '0 12px 34px rgba(16, 24, 40, 0.08)',
        card: '0 12px 30px rgba(16, 24, 40, 0.08)',
        cardHover: '0 18px 42px rgba(16, 24, 40, 0.13)',
        panel: '0 20px 60px rgba(16, 24, 40, 0.12)',
        floating: '0 18px 56px rgba(15, 23, 42, 0.16)',
        modal: '0 28px 80px rgba(16, 24, 40, 0.24)',
        glow: '0 0 0 1px rgba(91, 77, 255, 0.18), 0 18px 46px rgba(91, 77, 255, 0.18)',
        innerSubtle: 'inset 0 1px 0 rgba(255,255,255,0.78), inset 0 -1px 0 rgba(15,23,42,0.04)',
      },
      borderRadius: {
        xl: '0.875rem',
        '2xl': '1.125rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '0.875rem' }],
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.35rem' }],
        base: ['1rem', { lineHeight: '1.65rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.85rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.55rem' }],
        '5xl': ['3rem', { lineHeight: '3.25rem' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
